openapi: 3.0.0
info:
  title: Counter API
  version: 0.0.1
servers:
  - url: http://localhost:3030
basePath: /
schemes:
  - http
paths:
  /counter:
    get:
      summary: Retrieve the current counter
      tags:
        - counter
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
    delete:
      summary: Reset the counter to 0
      tags:
        - counter
      produces:
        - application/json
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter/increment:
    post:
      summary: Increment the counter
      tags:
        - counter
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter/decrement:
    post:
      summary: Decrement the counter
      tags:
        - counter
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter/double:
    post:
      summary: Double the counter
      tags:
        - counter
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter?value={number}:
    put:
      summary: Set the counter to a specific value via a query parameter
      tags:
        - extension 1
      produces:
        - application/json
      parameters:
        - name: value
          in: query
          description: The value to set the counter to
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter/{name}:
    get:
      summary: Retrieve the current counter for the provided counter name
      tags:
        - extension 2
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
    delete:
      summary: Reset the counter for the provided name to 0
      tags:
        - extension 2
      produces:
        - application/json
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter/{name}/increment:
    post:
      summary: Increment the counter for the provided name
      tags:
        - extension 2
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter/{name}/decrement:
    post:
      summary: Decrement the counter for the provided name
      tags:
        - extension 2
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
  /counter/{name}/double:
    post:
      summary: Double the counter for the provided name
      tags:
        - extension 2
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'


components:
  schemas:
    Counter: 
      type: object
      properties:
        counter: 
          type: integer